### ISSUE TITLE
Xlink multiple elements in one request

### ISSUE THREAD

**Issue by AdithyanIlangovan** [Dash-Industry-Forum/Conformance-and-reference-source#16]
According to the DASH standard, 
Xlink allows the resolution of one period element into multiple period elements. For instance

    <Period xlink:href="http://se-mashup.fokus.fraunhofer.de:8080/mws15/period_timescapes_komp" xlink:actuate="onLoad"/>

can be resolved into

    <?xml version="1.0" encoding="utf-8"?>
    <Period id=0>...</Period>
    <Period id=1>.</Period> 

The .mpd links to a remote element and the remote element contains multiple periods. 

If such an .mpd were fed in the dash conformance tool. Then it raises the following error:
>"SAXException: The markup in the document following the root element must be well-formed."

The problem could be that the DASH conformance tool still follows the old DASH standard (ISO/IEC 23009-1:2012), which allowed the remote entity to have only one top level element. Whereas, the new dash standard clearly states that the remote entity can have multiple top level elements (Section 5.5 in ISO/IEC 23009-1:2014). 

The conformance tool has to support remote entity with multiple top-level element.

**Comment by dsilhavy** [comment]
Hi @AdithyanIlangovan, 
the xlink:href URL you are referencing is not up to date. You can find the current examples here:
http://se-mashup.fokus.fraunhofer.de:8080/adinsertion-sample/xlink.html

Also we just changed the response type of an entity that has multiple top level elements to "text/plain". Nevertheless I think you are right regarding the error of the conformance tool.
Best regards 
Daniel
