### ISSUE TITLE
'lmsg' in STATIC MPDs with LIVE profiles on DASH-IF Website Dash Validator

### ISSUE THREAD

**Issue by richardbushell** [Dash-Industry-Forum/Conformance-and-reference-source#5]
We have a STATIC type MPD using a LIVE profile.
THe MPD is here:
http://living.tv/mob/ibeani_i4_mcstdlow_8000.mpd
Both we, and GPAC, have confirmed that the last segment generated contains the 'lmsg' brand, it still fails conformance, reporting:-
Brand 'lmsg' not found as a compatible brand for the last segment (number 8); violates Section 3.2.3. of Interoperability Point DASH264: If the MPD@type is equal to "dynamic" or if it includes MPD@profile attribute includes "urn:mpeg:dash:profile:isoff-live:2011", then: if the Media Segment is the last Media Segment in the Representation, this Media Segment shall carry the 'lmsg' compatibility brand.

This is a bug, please fix and advise.

Richard

**Comment by waqarz** [comment]
Thanks for reporting this. I can see the issue at line 1230 in ValidateAtomList.cpp . Would you like to provide a patch for this?

**Comment by richardbushell** [comment]
Sorry, not able to provide a patch myself, but it is a simple fix.

**Comment by waqarz** [comment]
Patched, SHA: 7d240c2bb724eea8e0b559c6db1184fbb6108766 
Synced online.

**Comment by richardbushell** [comment]
Thanks, I am out, but will double-check tonight...
Richard Bushell
MD, Living.TV
(Sent from my mobile phone)
On 7 Apr 2015 8:50 am, waqarz <notifications@github.com> wrote:Patched, SHA: 7d240c2 
Synced online.
