### ISSUE TITLE
never-ending validation of first representation (DVB-HbbTV profiles)

### ISSUE THREAD

**Issue by mprobst-irt** [Dash-Industry-Forum/Conformance-and-reference-source#76]
https://irtdashreference-i.akamaihd.net/dash/live/901161/bfs/manifestARD.mpd
produces an endless loop when entering validation of first representation

**Comment by niteeshbhat** [comment]
Fixed in https://github.com/Dash-Industry-Forum/Conformance-Software/pull/404
And deployed on the server. It works now.
